workflows:
  build_ios_unsigned:
    name: Build iOS Unsigned IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

      - name: Create IPA package
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r Runner.ipa Payload

    artifacts:
      - build/ios/iphoneos/Runner.ipa

    publishing:
      email:
        recipients:
          - hadi12hfh@gmail.com
